-- Phase 0: Governance tag taxonomy for SUPPLY_CHAIN.
-- Run after 00_setup_role.sql and all source_*.sql scripts.
USE ROLE SUPPLY_CHAIN_ADMIN;

CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN.GOVERNANCE
    COMMENT = 'Governance control plane: tags, classification results, and policy objects for the SUPPLY_CHAIN database.';

CREATE TAG IF NOT EXISTS SUPPLY_CHAIN.GOVERNANCE.SOURCE_SYSTEM
    ALLOWED_VALUES 'ERP','LOGISTICS_TMS','SUPPLIER_PORTAL','IOT_SENSOR','FINANCE'
    COMMENT = 'Identifies which fragmented Phase 0 source system an object originated from.';

CREATE TAG IF NOT EXISTS SUPPLY_CHAIN.GOVERNANCE.DATA_QUALITY_ISSUE
    COMMENT = 'Free-text tag capturing the specific genuine definitional/data-quality flaw documented on this Phase 0 table (see table COMMENT for detail).';

CREATE TAG IF NOT EXISTS SUPPLY_CHAIN.GOVERNANCE.LIFECYCLE
    ALLOWED_VALUES 'RAW_FRAGMENTED','BRONZE','CANONICAL_SILVER','CANONICAL_GOLD','GOVERNED_SEMANTIC'
    COMMENT = 'Medallion lifecycle stage of the object, matching the plan phases (RAW_FRAGMENTED = Phase 0).';

-- Apply SOURCE_SYSTEM + LIFECYCLE at the schema level (all objects in schema inherit the tag)
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_ERP SET TAG SUPPLY_CHAIN.GOVERNANCE.SOURCE_SYSTEM = 'ERP', SUPPLY_CHAIN.GOVERNANCE.LIFECYCLE = 'RAW_FRAGMENTED';
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS SET TAG SUPPLY_CHAIN.GOVERNANCE.SOURCE_SYSTEM = 'LOGISTICS_TMS', SUPPLY_CHAIN.GOVERNANCE.LIFECYCLE = 'RAW_FRAGMENTED';
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL SET TAG SUPPLY_CHAIN.GOVERNANCE.SOURCE_SYSTEM = 'SUPPLIER_PORTAL', SUPPLY_CHAIN.GOVERNANCE.LIFECYCLE = 'RAW_FRAGMENTED';
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_IOT_SENSOR SET TAG SUPPLY_CHAIN.GOVERNANCE.SOURCE_SYSTEM = 'IOT_SENSOR', SUPPLY_CHAIN.GOVERNANCE.LIFECYCLE = 'RAW_FRAGMENTED';
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_FINANCE SET TAG SUPPLY_CHAIN.GOVERNANCE.SOURCE_SYSTEM = 'FINANCE', SUPPLY_CHAIN.GOVERNANCE.LIFECYCLE = 'RAW_FRAGMENTED';

-- Apply DATA_QUALITY_ISSUE at the table level for the tables carrying each genuine flaw
ALTER TABLE SUPPLY_CHAIN.SOURCE_ERP.orders SET TAG SUPPLY_CHAIN.GOVERNANCE.DATA_QUALITY_ISSUE = 'EXCLUDES_CANCELLED_BACKORDER_FROM_OTD_DENOMINATOR';
ALTER TABLE SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS.deliveries SET TAG SUPPLY_CHAIN.GOVERNANCE.DATA_QUALITY_ISSUE = 'PROMISED_DATE_2DAY_BUFFER_AND_FREE_TEXT_SUPPLIER_NAME_VARIANTS';
ALTER TABLE SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS.freight_invoices SET TAG SUPPLY_CHAIN.GOVERNANCE.DATA_QUALITY_ISSUE = 'SHIPMENT_TO_INVOICE_ZERO_OR_ONE_GAP';
ALTER TABLE SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL.shipments SET TAG SUPPLY_CHAIN.GOVERNANCE.DATA_QUALITY_ISSUE = 'DROPS_IN_TRANSIT_FROM_OTD_DENOMINATOR';
ALTER TABLE SUPPLY_CHAIN.SOURCE_IOT_SENSOR.tracking_events SET TAG SUPPLY_CHAIN.GOVERNANCE.DATA_QUALITY_ISSUE = 'PARTIAL_70PCT_SENSOR_COVERAGE';
ALTER TABLE SUPPLY_CHAIN.SOURCE_FINANCE.daily_cogs SET TAG SUPPLY_CHAIN.GOVERNANCE.DATA_QUALITY_ISSUE = 'DOLLAR_BASED_DOI_METHODOLOGY_MISMATCH';
ALTER TABLE SUPPLY_CHAIN.SOURCE_FINANCE.overhead_allocation SET TAG SUPPLY_CHAIN.GOVERNANCE.DATA_QUALITY_ISSUE = 'ONE_MONTH_STALE_OVERHEAD_ALLOCATION';

-- Verify: tag references across all SUPPLY_CHAIN objects
-- SELECT * FROM TABLE(SUPPLY_CHAIN.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS('SUPPLY_CHAIN.SOURCE_ERP.ORDERS', 'table'));
