-- Phase 0: Data Quality Metric Functions (DMFs) — NOT YET APPLIED.
-- Deferred by user decision; kept here as a ready-to-run plan for later.
--
-- Prerequisite grants (one-time, requires ACCOUNTADMIN/SECURITYADMIN — already applied
-- to SUPPLY_CHAIN_ADMIN in this account as of this writing):
--   GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE SUPPLY_CHAIN_ADMIN;
--   GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE SUPPLY_CHAIN_ADMIN;
--   GRANT APPLY TAG ON ACCOUNT TO ROLE SUPPLY_CHAIN_ADMIN;

USE ROLE SUPPLY_CHAIN_ADMIN;

-- Run DMFs on every change (rows are only loaded via one-off INSERTs in this synthetic
-- Phase 0 dataset, so TRIGGER_ON_CHANGES keeps cost near zero until Bronze/Silver/Gold
-- pipelines start writing continuously).
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_ERP SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_IOT_SENSOR SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';
ALTER SCHEMA SUPPLY_CHAIN.SOURCE_FINANCE SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

-- SOURCE_ERP
ALTER TABLE SUPPLY_CHAIN.SOURCE_ERP.orders
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (erp_order_number),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (erp_order_number),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (order_status) USING (order_status -> order_status IN ('COMPLETE','CANCELLED','BACKORDER')),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (load_timestamp);

ALTER TABLE SUPPLY_CHAIN.SOURCE_ERP.demand_forecast
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (part_sku);

-- SOURCE_LOGISTICS_TMS
ALTER TABLE SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS.deliveries
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (pro_number),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (pro_number),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (load_timestamp);

ALTER TABLE SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS.pick_operations
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (pick_id);

ALTER TABLE SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS.freight_invoices
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (invoice_number);

-- SOURCE_SUPPLIER_PORTAL
ALTER TABLE SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL.shipments
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (asn_number),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (asn_number),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (shipment_status) USING (shipment_status -> shipment_status IN ('RECEIVED','IN_TRANSIT')),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (load_timestamp);

ALTER TABLE SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL.purchase_orders
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (po_number),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ACCEPTED_VALUES ON (po_status) USING (po_status -> po_status IN ('OPEN','CLOSED'));

ALTER TABLE SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL.freight_quotes
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (part_id);

-- SOURCE_IOT_SENSOR
ALTER TABLE SUPPLY_CHAIN.SOURCE_IOT_SENSOR.tracking_events
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (device_tag),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (load_timestamp);

-- SOURCE_FINANCE
ALTER TABLE SUPPLY_CHAIN.SOURCE_FINANCE.daily_cogs
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (part_id);

ALTER TABLE SUPPLY_CHAIN.SOURCE_FINANCE.overhead_allocation
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON (),
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (part_category);

-- After attaching, confirm associations with:
-- SELECT * FROM TABLE(SUPPLY_CHAIN.INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
--   REF_ENTITY_NAME => 'SUPPLY_CHAIN.SOURCE_ERP.ORDERS', REF_ENTITY_DOMAIN => 'table'));
