-- =============================================================================
-- Phase 4/8: Document Intelligence -- Cortex Search over supplier contracts
-- =============================================================================
-- This is the ONE genuinely unstructured data source in the project. Every
-- other Bronze/Silver/Gold table is structured (typed columns) or, at most,
-- semi-structured (SOURCE_IOT_SENSOR's nested sensor JSON). Supplier
-- contracts are free-form legal prose -- payment terms and SLA penalty
-- clauses buried in paragraphs, not columns -- which is exactly why they
-- need AI_PARSE_DOCUMENT + Cortex Search rather than a relational table.
--
-- Pipeline: PDF (unstructured) -> stage -> AI_PARSE_DOCUMENT (LAYOUT mode,
-- text extraction) -> supplier_contract_documents (parsed text table) ->
-- Cortex Search service -> DocumentQAAgent (agents/agent_router.py) and the
-- post-query enrichment hook.
--
-- Source PDFs are generated by data_generation/generate_supplier_contracts.py
-- (11 synthetic supplier contracts, deterministic per supplier, varying
-- payment terms and late-delivery penalty clauses -- one supplier
-- deliberately has NO penalty clause as a negative-case test).
--
-- IMPORTANT: AI_PARSE_DOCUMENT incurs Cortex AI function usage cost. Check
-- current rates before running: https://docs.snowflake.com/en/user-guide/cost-understanding-overall#service-type
-- =============================================================================

USE ROLE SUPPLY_CHAIN_ADMIN;

-- One-time grant (requires ACCOUNTADMIN/SECURITYADMIN) needed for AI_PARSE_DOCUMENT.
-- USE ROLE ACCOUNTADMIN;
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SUPPLY_CHAIN_ADMIN;
-- USE ROLE SUPPLY_CHAIN_ADMIN;

CREATE STAGE IF NOT EXISTS SUPPLY_CHAIN.SEMANTIC_MODELS.SUPPLIER_CONTRACTS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Unstructured supplier contract PDFs (payment terms, SLA penalty clauses). Feeds AI_PARSE_DOCUMENT -> Cortex Search for the document-intelligence demo moment.';

-- Upload PDFs from data_generation/supplier_contracts/*.pdf to this stage before
-- continuing, e.g. via SnowSQL/Python connector PUT:
--   PUT 'file://<repo>/data_generation/supplier_contracts/*.pdf'
--       @SUPPLY_CHAIN.SEMANTIC_MODELS.SUPPLIER_CONTRACTS_STAGE
--       AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

ALTER STAGE SUPPLY_CHAIN.SEMANTIC_MODELS.SUPPLIER_CONTRACTS_STAGE REFRESH;

CREATE OR REPLACE TABLE SUPPLY_CHAIN.SEMANTIC_MODELS.supplier_contract_documents (
    supplier_id VARCHAR COMMENT 'Extracted from filename, e.g. SUP-0002_contract.pdf -> SUP-0002.',
    file_name VARCHAR,
    parsed_content VARCHAR COMMENT 'Full contract text extracted via AI_PARSE_DOCUMENT (LAYOUT mode) -- unstructured source, no structured payment_terms/penalty columns exist upstream; Cortex Search reads this text directly.',
    page_count NUMBER,
    parsed_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Unstructured document intelligence: AI_PARSE_DOCUMENT output over synthetic supplier contract PDFs. Feeds the Cortex Search service used by the DocumentQAAgent (agents/agent_router.py) and the post-query enrichment hook.';

INSERT INTO SUPPLY_CHAIN.SEMANTIC_MODELS.supplier_contract_documents (supplier_id, file_name, parsed_content, page_count)
SELECT
    SPLIT_PART(relative_path, '_', 1) AS supplier_id,
    relative_path AS file_name,
    parsed:content::STRING AS parsed_content,
    parsed:metadata:pageCount::NUMBER AS page_count
FROM (
    SELECT
        relative_path,
        AI_PARSE_DOCUMENT(
            TO_FILE('@SUPPLY_CHAIN.SEMANTIC_MODELS.SUPPLIER_CONTRACTS_STAGE', relative_path),
            {'mode': 'LAYOUT'}
        ) AS parsed
    FROM DIRECTORY(@SUPPLY_CHAIN.SEMANTIC_MODELS.SUPPLIER_CONTRACTS_STAGE)
    WHERE relative_path ILIKE '%.pdf'
);

CREATE OR REPLACE CORTEX SEARCH SERVICE SUPPLY_CHAIN.SEMANTIC_MODELS.SUPPLY_CHAIN_DOCUMENTS
    ON parsed_content
    ATTRIBUTES supplier_id, file_name
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 HOUR'
    COMMENT = 'Cortex Search over AI_PARSE_DOCUMENT-parsed supplier contract PDFs (payment terms, SLA penalty clauses). Feeds the DocumentQAAgent and the agent router''s post-query enrichment hook -- the document-intelligence demo moment: "Does our contract with Supplier X have an SLA penalty for late delivery?"'
    AS (
        SELECT supplier_id, file_name, parsed_content
        FROM SUPPLY_CHAIN.SEMANTIC_MODELS.supplier_contract_documents
    );

-- -----------------------------------------------------------------------------
-- Validation -- the plan's exact document-intelligence demo moment
-- -----------------------------------------------------------------------------

SELECT PARSE_JSON(
  SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
    'SUPPLY_CHAIN.SEMANTIC_MODELS.SUPPLY_CHAIN_DOCUMENTS',
    '{"query": "Does our contract with Supplier 002 have an SLA penalty for late delivery?", "columns": ["supplier_id","file_name","parsed_content"], "limit": 2}'
  )
) AS result;
