-- =============================================================================
-- Phase 1: Bronze Layer — ingest Phase 0 SOURCE_* systems (11 tables)
-- =============================================================================
-- Pattern: explicit typed-column INSERT ... SELECT for all structured sources.
-- Each source column maps 1:1 to a Bronze typed column — no OBJECT_CONSTRUCT(*)
-- wrapper. _METADATA records which source system/table/timestamp each row came
-- from, enabling Silver's shipment_crosswalk to trace a canonical shipment back
-- to its originating fragmented record.
--
-- Exception: tracking_events (IoT) keeps EVENT_PAYLOAD as VARIANT passthrough
-- since its payload is genuinely semi-structured (nested sensor JSON with
-- variable noise fields).
-- =============================================================================

USE ROLE SUPPLY_CHAIN_ADMIN;
USE SCHEMA SUPPLY_CHAIN.BRONZE;

INSERT INTO ORDERS (ERP_ORDER_NUMBER, SUPPLIER_CODE, PART_SKU, REQUESTED_SHIP_DATE, ACTUAL_SHIP_DATE, ORDER_STATUS, QUANTITY, _METADATA)
SELECT
    ERP_ORDER_NUMBER, SUPPLIER_CODE, PART_SKU, REQUESTED_SHIP_DATE, ACTUAL_SHIP_DATE, ORDER_STATUS, QUANTITY,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_ERP', 'source_table', 'ORDERS', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_ERP.orders;

INSERT INTO DELIVERIES (PRO_NUMBER, CARRIER_NAME, ORIGIN_SUPPLIER_NAME, PROMISED_DELIVERY_DATE, FIRST_DELIVERY_ATTEMPT_DATE, FINAL_DELIVERY_DATE, IS_PARTIAL_SHIPMENT, _METADATA)
SELECT
    PRO_NUMBER, CARRIER_NAME, ORIGIN_SUPPLIER_NAME, PROMISED_DELIVERY_DATE, FIRST_DELIVERY_ATTEMPT_DATE, FINAL_DELIVERY_DATE, IS_PARTIAL_SHIPMENT,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_LOGISTICS_TMS', 'source_table', 'DELIVERIES', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS.deliveries;

INSERT INTO SHIPMENTS (ASN_NUMBER, SUPPLIER_ID_PORTAL, PART_NUMBER_PORTAL, PLANT_CODE, PLANNED_RECEIPT_DATE, ACTUAL_RECEIPT_DATE, SHIPMENT_STATUS, QUANTITY, _METADATA)
SELECT
    ASN_NUMBER, SUPPLIER_ID_PORTAL, PART_NUMBER_PORTAL, PLANT_CODE, PLANNED_RECEIPT_DATE, ACTUAL_RECEIPT_DATE, SHIPMENT_STATUS, QUANTITY,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_SUPPLIER_PORTAL', 'source_table', 'SHIPMENTS', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL.shipments;

-- tracking_events: DEVICE_TAG as typed column, EVENT_PAYLOAD as VARIANT passthrough
INSERT INTO TRACKING_EVENTS (DEVICE_TAG, EVENT_PAYLOAD, _METADATA)
SELECT
    DEVICE_TAG, EVENT_PAYLOAD,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_IOT_SENSOR', 'source_table', 'TRACKING_EVENTS', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_IOT_SENSOR.tracking_events;

INSERT INTO PURCHASE_ORDERS (PO_NUMBER, SUPPLIER_ID_PORTAL, PART_NUMBER_PORTAL, QTY_ORDERED, QTY_RECEIVED, PO_STATUS, _METADATA)
SELECT
    PO_NUMBER, SUPPLIER_ID_PORTAL, PART_NUMBER_PORTAL, QTY_ORDERED, QTY_RECEIVED, PO_STATUS,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_SUPPLIER_PORTAL', 'source_table', 'PURCHASE_ORDERS', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL.purchase_orders;

INSERT INTO PICK_OPERATIONS (PICK_ID, CUSTOMER_ORDER_REF, UNITS_ORDERED, UNITS_PICKED, _METADATA)
SELECT
    PICK_ID, CUSTOMER_ORDER_REF, UNITS_ORDERED, UNITS_PICKED,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_LOGISTICS_TMS', 'source_table', 'PICK_OPERATIONS', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS.pick_operations;

INSERT INTO DEMAND_FORECAST (PART_SKU, FORECAST_MONTH, FORECASTED_DAILY_DEMAND, _METADATA)
SELECT
    PART_SKU, FORECAST_MONTH, FORECASTED_DAILY_DEMAND,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_ERP', 'source_table', 'DEMAND_FORECAST', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_ERP.demand_forecast;

INSERT INTO DAILY_COGS (PART_ID, COGS_DATE, DAILY_COGS, _METADATA)
SELECT
    PART_ID, COGS_DATE, DAILY_COGS,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_FINANCE', 'source_table', 'DAILY_COGS', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_FINANCE.daily_cogs;

INSERT INTO FREIGHT_INVOICES (INVOICE_NUMBER, PRO_NUMBER, FREIGHT_COST, CUSTOMS_DUTY, INVOICE_DATE, _METADATA)
SELECT
    INVOICE_NUMBER, PRO_NUMBER, FREIGHT_COST, CUSTOMS_DUTY, INVOICE_DATE,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_LOGISTICS_TMS', 'source_table', 'FREIGHT_INVOICES', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_LOGISTICS_TMS.freight_invoices;

INSERT INTO OVERHEAD_ALLOCATION (PART_CATEGORY, MONTH, ALLOCATED_OVERHEAD_PER_UNIT, _METADATA)
SELECT
    PART_CATEGORY, MONTH, ALLOCATED_OVERHEAD_PER_UNIT,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_FINANCE', 'source_table', 'OVERHEAD_ALLOCATION', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_FINANCE.overhead_allocation;

INSERT INTO FREIGHT_QUOTES (PART_ID, FREIGHT_ESTIMATE, _METADATA)
SELECT
    PART_ID, FREIGHT_ESTIMATE,
    OBJECT_CONSTRUCT('source_system', 'SOURCE_SUPPLIER_PORTAL', 'source_table', 'FREIGHT_QUOTES', 'ingested_at', CURRENT_TIMESTAMP())
FROM SUPPLY_CHAIN.SOURCE_SUPPLIER_PORTAL.freight_quotes;
