[theme]
primaryColor = "#29B5E8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#11567F"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false
